services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development

  frontend:
    build:
      context: .
      dockerfile: ./frontend_DEPRECATED/Dockerfile
    volumes:
      - ./frontend_DEPRECATED:/app
      # Zorg ervoor dat node_modules niet wordt overschreven
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
